[identity]
namespace = "examplemod"
name = "Outergrowth Example Mod"
description = "An example mod showcasing how to use the Outergrowth & TVE Modding API"
version = "1.0.0-alpha.1"

[authors]
creators = ["NeusFear"]
contributors = ["Jaskarth"]

[dependencies]
required = []
optional = ["examplemod:1.0.0"]